language: python
sudo: false

#power_jobs
arch: ppc64le

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: pypy3
branches:
  only:
    - master

before_install:
  - pip install -U setuptools pip wheel

install:
  - python -V
  - pip install .

script:
  - ./tests.py
  - python mypy_run.py

