language: python
sudo: false

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: pypy3
#power_jobs
    - python: 3.5
      arch: ppc64le
    - python: 3.6
      arch: ppc64le
    - python: 3.7
      dist: xenial
      sudo: true
      arch: ppc64le
# Disable version pypy3
jobs: 
  exclude:
    - arch: ppc64le
      python: pypy3
      
branches:
  only:
    - master

before_install:
  - pip install -U setuptools pip wheel

install:
  - python -V
  - pip install .

script:
  - ./tests.py
  - python mypy_run.py

